### ISSUE TITLE
No unity file can be loaded

### ISSUE THREAD

**Issue by Ghost-opbr** [aelurum/AssetStudio#48]
![ddss](https://github.com/user-attachments/assets/9aaccadf-da23-4fc9-8177-a102fe8d00d7)
i cant open the file, its build on unity 2021.3.28f1 . is there any way to fix this? 

the file im trying to open: https://easyupload.io/ooi0c2

**Comment by aelurum** [comment]
Something is wrong with the block info data
You can try to ask about this in [UnityPy](https://github.com/K0lb3/UnityPy/) Discord server
